routes.py
import flask
import httpx

import settings
import utils

main = flask.Blueprint('main', __name__, template_folder='templates')


@main.route('/', methods=['GET'])
def get_main():
    """
    Render the main page with a list of available requests.
    """
    return flask.render_template('main.html')


@main.route('/search', methods=['GET', 'POST'])
def search():
    """
    An endpoint for retrieving initial filtered hotels records with a search word given.
    """
    if flask.request.method == 'POST':
        search_word = flask.request.form.get('search_word')
        flask.session['search_word'] = search_word
        return flask.redirect(flask.url_for('main.get_filtered_hotels'))
    return flask.render_template('search.html')


@main.route('/filtered_hotels', methods=['GET', 'POST'])
async def get_filtered_hotels():
    """
    Retrieve filtered hotel records based on a search word.

    Sets a 'search_word' parameter into the user session to support filtered iteration.
    """
    request = flask.request
    page, limit = utils.get_page_and_limit(request)
    base_request_url = (f'http://{settings.HOTELS_BACKEND_HOST}:{settings.HOTELS_BACKEND_PORT}'
                        f'/hotels/retrieve_filtered')
    built_url = utils.build_url_to_request(page=page, limit=limit, url=base_request_url)

    search_word = flask.session.get('search_word')
    async with httpx.AsyncClient() as client:
        response = await client.post(url=built_url, data=f'"{search_word}"')
        data = response.json()

    return flask.render_template('table.html', **data)


@main.route('/all_hotels', methods=['GET', 'POST'])
async def get_all_hotels():
    """
    Retrieve all hotel records.

    Shares a template for displaying entries with the 'get_filtered_hotels' route.
    Clears the 'search_word' from the user session to iterate over data without filters applied.
    """
    if 'search_word' in flask.session:
        flask.session.pop('search_word')

    request = flask.request
    page, limit = utils.get_page_and_limit(request)
    base_request_url = (f'http://{settings.HOTELS_BACKEND_HOST}:{settings.HOTELS_BACKEND_PORT}'
                        f'/hotels/retrieve')
    built_url = utils.build_url_to_request(page=page, limit=limit, url=base_request_url)

    async with httpx.AsyncClient() as client:
        response = await client.get(url=built_url)
        data = response.json()

    return flask.render_template('table.html', **data)

templates/base.html
<!DOCTYPE html>
<html lang="en">

{% block head %}
  <head>
    <title>{% block title %}Title{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static.static', filename='style.css') }}">
  </head>
{% endblock %}

<body>

<br><br><br><br>
{% block nav %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col col-auto">
        <nav class="navbar navbar-expand-lg">
          <div class="navbar-nav">
            <a class="nav-link" href="{{ url_for('main.get_main') }}"> To the main
              page</a>
            <a class="nav-link {% if request.endpoint == 'main.search'
            or request.endpoint == 'main.get_filtered_hotels' %}active{% endif %}"
               href="{{ url_for('main.search') }}">Filter hotels by a specific
              word</a>
            <a class="nav-link {% if request.endpoint == 'main.get_all_hotels' %}active{% endif %}"
               href="{{ url_for('main.get_all_hotels') }}">Retrieve all hotels</a>
          </div>
        </nav>
      </div>
    </div>
  </div>
{% endblock %}
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="col col-auto">
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col col-auto">
      {% block pagination %}
      {% endblock %}
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col col-auto">
      {% block input %}
      {% endblock %}
    </div>
  </div>
</div>
{% block bootstrap %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
          crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>

templates/main.html
{% extends 'base.html' %}

{% block nav %}
{% endblock %}

{% block title %}
  Main page
{% endblock %}

{% block content %}
  <div class="list-group">
    <a href="{{ url_for('main.search') }}" class="list-group-item list-group-item-action"
       aria-current="true">
      Filter hotels by a specific word
    </a>
    <a href="{{ url_for('main.get_all_hotels') }}" class="list-group-item list-group-item-action">
      Retrieve all hotels
    </a>
  </div>
{% endblock %}

templates/pagination.html
<nav aria-label="Page navigation">
  <ul class="pagination justify-content-center">
    {% if current_page > 1 %}
      <li class="page-item">
        <a class="page-link" href="?page=1" aria-label="First">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ current_page - 1 }}&limit={{ limit }}"
           aria-label="Previous">
          <span aria-hidden="true">&lsaquo;</span>
        </a>
      </li>
    {% endif %}

    {% for page_num in range(1, pages + 1) %}
      {% if page_num == 1 %}
        <li class="page-item {% if page_num == current_page %}active{% endif %}">
          <a class="page-link"
             href="?page={{ page_num }}&limit={{ limit }}">{{ page_num }}</a>
        </li>
      {% elif page_num == pages %}
        <li class="page-item {% if page_num == current_page %}active{% endif %}">
          <a class="page-link"
             href="?page={{ page_num }}&limit={{ limit }}">{{ page_num }}</a>
        </li>
      {% elif current_page - 1 <= page_num <= current_page + 1 %}
        <li class="page-item {% if page_num == current_page %}active{% endif %}">
          <a class="page-link"
             href="?page={{ page_num }}&limit={{ limit }}">{{ page_num }}</a>
        </li>
      {% elif page_num == current_page - 2 or page_num == current_page + 2 %}
        <li class="page-item">
          <a class="page-link">...</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if current_page < pages %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ current_page + 1 }}&limit={{ limit }}"
           aria-label="Next">
          <span aria-hidden="true">&rsaquo;</span>
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ pages }}&limit={{ limit }}"
           aria-label="Last">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>

templates/search.html
{% extends 'base.html' %}
{% block title %}
  Search
{% endblock %}

{% block content %}
  <form method="POST">
    <div class="container">
      <div class="row justify-content-center">
        <div class="input-group mb-3 col col-auto">
          <input type="text" class="form-control" placeholder="Enter search word"
                 aria-label="Search word" aria-describedby="basic-addon2" minlength="3"
                 name="search_word" autocomplete="off" pattern="^\S(.*\S)?$"
                 required>
          <button type="submit" class="btn btn-outline-primary" id="basic-addon2">Search</button>
        </div>
      </div>
    </div>
  </form>
{% endblock %}

templates/table.html
{% extends "base.html" %}

{% block title %}
  Records
{% endblock %}

{% block content %}
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Country</th>
      <th scope="col">City</th>
    </tr>
    </thead>
    <tbody>
    {% set loop_counter = namespace(counter=1) %}
    {% for hotel in hotels %}
      <tr>
        <th scope="row">{{ loop_counter.counter }}</th>
        <td>{{ hotel.name }}</td>
        <td>{{ hotel.country }}</td>
        <td>{{ hotel.city }}</td>
      </tr>
      {% set loop_counter.counter = loop_counter.counter + 1 %}
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

{% block pagination %}
  {% include "pagination.html" %}
{% endblock %}

{% block input %}
  <form method="POST">
    <div class="container">
      <div class="row">
        <div class="input-group mb-3 col col-auto">
          <input type="number" class="form-control" placeholder="Table rows limit"
                 aria-label="Table rows limit" aria-describedby="basic-addon2" min="1"
                 name="limit">
          <button type="submit" class="btn btn-outline-primary" id="basic-addon2">Change</button>
        </div>
      </div>
    </div>
  </form>
{% endblock %}